adam_b1: 0.9
adam_b2: 0.999
cuda: true
data_norm: meanstd
data_subset: 1.
devices: 0
dryrun: false
eval_patchsize: 128
iterations_before_val: 1000
lr: 0.00015837006124497214
max_iterations: 86188
mbs: 68
num_workers: 8
optimizer: adam
patchsize: 92
seed: 1341
trainer: cnn10
valsamples: 8
