adam_b1: 0.3260552006030955
adam_b2: 0.999
cuda: true
data_norm: meanstd
data_subset: 1.
devices: 0
dryrun: false
max_iterations: 67306
iterations_before_val: 1000
lam_perc: 0.6893269329076448
lr: 7.096903581620458e-05
mbs: 77
n_d_train: 1
num_workers: 4
optimizer: adam
patchsize: 77
seed: 1344
trainer: wganvgg
valsamples: 8
